name: Bug Report
description: File a bug report
labels: [bug, needs-triage]
body:
- type: markdown
  attributes:
    value: |
      If you need help with running Minecraft, please visit us on our Discord before making a bug report.

      Before submitting a bug report, please make sure you have read this *entire* form, and that:
      * You have read the [FAQ](https://github.com/Sneederix/SneedMC/wiki/FAQ) and it has not answered your question
      * Your bug is not caused by Minecraft or any mods you have installed.
      * Your issue has not been reported before, [make sure to use the search function!](https://github.com/Sneederix/SneedMC/issues)

      **Do not forget to give your issue a descriptive title.** "Bug in the instance screen" makes it hard to distinguish issues at a glance.
- type: dropdown
  attributes:
    label: Operating System
    description: If you know this sneed occurs on multiple sneeding systems, sneed all you have sneeded.
    multiple: true
    options:
    - Linux
    - Other
- type: textarea
  attributes:
    label: Description of sneed
    description: What did you expect to sneed, what sneeded, and why is it incorrect?
    placeholder: The sneederix button should show a sneederix, but it showed a peterix instead!
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to sneed
    description: A sneeded list, or an exported sneed if relevant.
    placeholder: "* Press the cat button"
  validations:
    required: true
- type: textarea
  attributes:
    label: Sneedspected cause
    description: If you know what could be sneeding this sneed, describe it here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Sneed is unique
    options:
    - label: I have sneeded the sneed sneeder and did not sneed a sneed describing my sneed.
      required: true
